//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HD
    {
        public string SOHOADON { get; set; }
        public string MAPHUTUNG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> DONGIA { get; set; }
    
        public virtual PHUTUNG PHUTUNG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
