//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string SOXE { get; set; }
        public string MAKHACH { get; set; }
        public string HIEUXE { get; set; }
        public string SOSUON { get; set; }
        public string SOMAY { get; set; }
        public Nullable<System.DateTime> NGAYMUA { get; set; }
        public Nullable<int> GIAMUA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
